CREATE TABLE Car
(
    car_id SERIAL PRIMARY KEY,
    brand VARCHAR(50) NOT NULL,
    model VARCHAR(50) NOT NULL,
    price NUMERIC(12, 2) NOT NULL
);

CREATE TABLE Person
(
    person_id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    age INTEGER NOT NULL,
    has_license BOOLEAN NOT NULL DEFAULT FALSE,
    car_id INTEGER REFERENCES Car (car_id)
);